update

diff --git a/dot_local/bin/executable_git-fzf b/dot_local/bin/executable_git-fzf
--- a/dot_local/bin/executable_git-fzf
+++ b/dot_local/bin/executable_git-fzf
@@ -6,73 +6,119 @@ if ! type -p fzf > /dev/null; then
 fi
 
 GIT_FZF_SELECT_KEY_BINDINGS=`cat <<_BINDING_
---bind ctrl-a:select-all
---bind ctrl-x:deselect-all
---bind ctrl-d:preview-page-down
---bind ctrl-u:preview-page-up
+ctrl-a:select-all
+ctrl-x:deselect-all
+ctrl-d:preview-page-down
+ctrl-u:preview-page-up
+_BINDING_`
+
+GIT_FZF_PREVIEW_KEY_BINDINGS=`cat <<_BINDING_
+down,j:down
+up,k:up
+ctrl-j:preview-down
+ctrl-k:preview-up
+ctrl-d:preview-page-down
+ctrl-u:preview-page-up
+q,ctrl-c:abort
 _BINDING_`
 
 GIT_FZF_HEIGHT_OPTS=${GIT_FZF_HEIGHT_OPTS:=--tmux center,100%,80%}
 GIT_FZF_DEFAULT_OPTS=${GIT_FZF_DEFAULT_OPTS:=--ansi --no-sort --style=full --layout=reverse $GIT_FZF_HEIGHT_OPTS}
 
-GIT_FZF_FILE_PREVIEW_COMMAND=${GIT_FZF_FILE_PREVIEW_COMMAND:-"bat -f"}
+GIT_FZF_FILE_PREVIEW_COMMAND=${GIT_FZF_FILE_PREVIEW_COMMAND:-"bat -f --style=numbers"}
 GIT_FZF_DIFF_COMMAND=${GIT_FZF_DIFF_COMMAND:-"git diff --color"}
 
-fzf_preview_select() {
-  fzf $GIT_FZF_DEFAULT_OPTS $GIT_FZF_SELECT_KEY_BINDINGS --preview "$1"
+_fzf() {
+  local preview_command="$1"
+  local opts="$GIT_FZF_DEFAULT_OPTS"
+
+  [[ -n $EXTRA_OPTS ]] && opts="$opts $EXTRA_OPTS"
+  [[ -n $FILTER ]] && opts="$opts --filter '$FILTER'"
+  [[ -n $BINDING ]] && opts="$opts $(awk '{print "--bind",$0}' <<<"$BINDING")"
+
+  SHELL=/bin/bash fzf $opts --preview "$preview_command"
 }
 
-fzf_preview_multi_select() {
-  fzf $GIT_FZF_DEFAULT_OPTS $GIT_FZF_SELECT_KEY_BINDINGS --multi --preview "$1"
+_preview() {
+  BINDING="$GIT_FZF_PREVIEW_KEY_BINDINGS" \
+  EXTRA_OPTS="$EXTRA_OPTS --disabled --no-input" \
+  _fzf "$1"
 }
 
-fzf_preview() {
-  fzf $GIT_FZF_DEFAULT_OPTS --disabled --no-input \
-    --bind 'down,j:down' \
-    --bind 'up,k:up' \
-    --bind 'ctrl-j:preview-down' \
-    --bind 'ctrl-k:preview-up' \
-    --bind 'ctrl-d:preview-page-down' \
-    --bind 'ctrl-u:preview-page-up' \
-    --bind 'q,ctrl-c:abort' \
-    --preview "$1"
+_preview_select() {
+  BINDING="$GIT_FZF_SELECT_KEY_BINDINGS" EXTRA_OPTS="$EXTRA_OPTS --select-1" _fzf "$1"
+}
+
+_preview_multi_select() {
+  BINDING="$GIT_FZF_SELECT_KEY_BINDINGS" EXTRA_OPTS="$EXTRA_OPTS --multi" _fzf "$1"
+}
+
+_diff() {
+  git -c color.status=always status --short | $* '
+    line=$(tr -d "$'\''" <<<"{}")
+    if [[ $line =~ ^\?\? ]]; then
+      '"$GIT_FZF_FILE_PREVIEW_COMMAND"' {-1}
+    else
+      cached=$([[ $line =~ ^M ]] && echo --cached)
+      git diff $cached {-1} | '"$GIT_FZF_FILE_PREVIEW_COMMAND"'
+    fi
+  '
 }
 
 fzf_add() {
-  git status --short |
-    fzf_preview_multi_select "$GIT_FZF_DIFF_COMMAND {2}" | \
-   awk '{print $2}' | xargs -r git add
+  _diff _preview_multi_select | awk '{print $NF}' | xargs -r git add -v
 }
 
 fzf_log() {
-  git log --pretty='format:%C(auto)%h %s' --color |
-    fzf_preview 'git log -p {1} -n1 --color --decorate --stat \
+  git log --pretty='format:%C(auto)%h %s' --color "$*" |
+    _preview 'git log -p {1} -n1 --color --decorate --stat \
                 --pretty="format:%C(auto)commit: %H%nref: %D%nauthor: %an <%ae>%ndate: %ad%n"'
 }
 
-fzf_ls_file() {
-  git ls-files | fzf_preview "$GIT_FZF_FILE_PREVIEW_COMMAND {1}"
+fzf_ls_files() {
+  git ls-files | _preview "$GIT_FZF_FILE_PREVIEW_COMMAND {1}"
 }
 
 fzf_restore() {
-  git -c color.ui=never status --short | awk '/^.[MDU] +/{print $2}' | xargs git status --short |
-    fzf_preview_multi_select "$GIT_FZF_DIFF_COMMAND {2}" | awk '{print $2}' | xargs -r -t git restore
+  _diff _preview_multi_select | awk '{print $NF}' | xargs -r -x git restore
+}
+
+fzf_commit_fixup() {
+  if git diff --cached --quiet; then
+    warn "No staged changes found"
+    exit 1
+  fi
+
+  default_branch="$(git branch | awk '$NF~/master|main/{print $NF}')"
+  EXTRA_OPTS="--accept-nth {1}" fzf_log ${default_branch}..$(git branch --show-current) |
+    xargs -r -x git commit --fixup
+}
+
+fzf_diff() {
+  _diff _preview
 }
 
 fzf_switch() {
   git branch --sort=-committerdate | grep -v '^\*' | fzf -1 | xargs -r git switch
 }
 
+warn() {
+  echo -en "\033[31m" >&2
+  echo "$*" >&2
+  echo -en "\033[0m" >&2
+}
+
 ACTION=$1; shift
-OPTS=$@
 case $ACTION in
   add) fzf_add ;;
-  log) fzf_log ;;
-  ls-files) fzf_ls_file ;;
+  commit-fixup) fzf_commit_fixup ;;
+  diff) fzf_diff ;;
+  log) fzf_log > /dev/null ;;
+  ls-files) fzf_ls_files > /dev/null ;;
   restore) fzf_restore ;;
   switch) fzf_switch ;;
   *)
-    echo -e "\033[31mInvalid action\033[0m"
+    warn "Invalid action"
     exit 1
     ;;
 esac
